site_name: Physics and Mathematics
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
markdown_extensions:
  - toc
  - tables
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - mermaid2

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Physics:
      - Mechanics:
          - Problem 1: "1_Physics/1_Mechanics/Problem_1.md"
          - Problem 2: "1_Physics/1_Mechanics/Problem_2.md"
      - Gravity:
          - Problem 1: "1_Physics/2_Gravity/Problem_1.md"
          - Problem 2: "1_Physics/2_Gravity/Problem_2.md"
          - Problem 3: "1_Physics/2_Gravity/Problem_3.md"
      - Waves:
          - Problem 1: "1_Physics/3_Waves/Problem_1.md"
      - Circuits:
          - Problem 1: "1_Physics/4_Circuits/Problem_1.md"
      - Electromagnetism:
          - Problem 1: "1_Physics/5_Electromagnetism/Problem_1.md"
      - Statistics:
          - Problem 1: "1_Physics/6_Statistics/Problem_1.md"
          - Problem 2: "1_Physics/6_Statistics/Problem_2.md"
      - Measurements:
          - Problem 1: "1_Physics/7_Measurements/Problem_1.md"


    